dual: true
pandoc_common:
  input_files:
  - sampleTeachingExtensions.md
  output_basename:
    SP: ejemploExtensiones
    EN: sampleTeachingExtensions
pandoc_targets:
  PDF:
    options: -t latex -s
